// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/alanwade2001/spa-initiation-api/repositories"
	"github.com/alanwade2001/spa-initiation-api/routers"
	"github.com/alanwade2001/spa-initiation-api/services"
	"github.com/alanwade2001/spa-initiation-api/types"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitialiseServerAPI() types.ServerAPI {
	engine := gin.Default()
	repositoryAPI := repositories.NewMongoRepository()
	initiationAPI := routers.NewInitiationRouter(repositoryAPI)
	registerAPI := routers.NewRegisterService(engine, initiationAPI)
	configAPI := services.NewConfigService()
	serverAPI := NewServer(engine, registerAPI, configAPI)
	return serverAPI
}
